from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create router and register ViewSets
router = DefaultRouter()
router.register(r'image-assets', views.ImageAssetViewSet)
router.register(r'beetles', views.BeetlesViewSet, basename='beetles')
router.register(r'species', views.SpeciesViewSet, basename='species')

# API URLs are automatically generated by the router
urlpatterns = router.urls
