from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create router and register ViewSets
router = DefaultRouter()
router.register(r'image-assets', views.ImageAssetViewSet)
router.register(r'beetles', views.BeetlesViewSet, basename='beetles')
router.register(r'species', views.SpeciesViewSet, basename='species')
router.register(r'bounding-boxes', views.BoundingBoxViewSet, basename='bounding-boxes')

# Custom API endpoints (must come before router.urls)
custom_urls = [
    path('export-annotations/', views.export_annotations_view, name='export-annotations'),
]

# API URLs are automatically generated by the router
urlpatterns = custom_urls + router.urls
