services:
  web:
    command: pixi run gunicorn --timeout 120
    restart: always
    volumes:
      - /root/barkandambrosia_data/media:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  db:
    restart: always
    volumes:
      # OVERRIDE the data location
      - /root/barkandambrosia_data/postgres:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports: []

  # REDIS
  redis:
    restart: always

  # CELERY WORKER
  worker:
    restart: always
    # Concurrency 1 is important for your server size
    command: pixi run celery -A beetlesgallery worker -l info --concurrency=1
    volumes:
      # MUST match the web volumes so worker can see the files!
      - /root/barkandambrosia_data/media:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis