services:
  web:
    build: .
    command: pixi run gunicorn --workers 25 --timeout 600
    restart: always
    ports:
      - "80:8000"
    volumes:
      - /opt/barkandambrosia_data/media:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    volumes:
      - /opt/barkandambrosia_data/postgres:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports: []

  redis:
    image: redis:7-alpine
    restart: always

  worker:
    build: .
    restart: always
    command: pixi run celery -A beetlesgallery worker -l info --concurrency=1
    volumes:
      - /opt/barkandambrosia_data/media:/app/media
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis
