services:
  web:
    volumes:
      - .:/app          # Hot-reloading for code
      - /app/.pixi      # The fix for Windows/Linux permission crash
      - media_data:/app/media

  db:
    ports:
      - "5432:5432"