"""
Django settings for beetlesgallery project.

Generated by 'django-admin startproject' using Django 5.0.1.
"""

import os
import subprocess
import dj_database_url
from pathlib import Path

# 1. Capture the production version if available
APP_VERSION = os.environ.get('APP_VERSION')

# 2. Fallback for development: Get short git commit hash
if not APP_VERSION:
    try:
        # Runs 'git rev-parse --short HEAD' to get the current hash (e.g., a1b2c3d)
        APP_VERSION = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).decode('utf-8').strip()
    except Exception:
        APP_VERSION = 'dev-build'

# 3. Ensure DEBUG is accessible to determine environment in templates
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Defaults to a dev key if not found in environment
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-fallback-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Allow hosts from environment, split by comma
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'beetlesgallery.apps.GalleryStaticFilesConfig',  # django.contrib.staticfiles, without the Tailwind source
    'django.contrib.humanize',      # Required for template filters
    
    # Third-party libraries
    'simple_history',
    'crispy_forms',
    'django_filters',
    'rest_framework',
    'rest_framework.authtoken',
    'treebeard',

    # Local App (Internal Module)
    'beetlesgallery.beetles_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',  # Added for simple_history
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'beetlesgallery.beetles_app.middleware.UserTimezoneMiddleware',  # Show times in the viewer's timezone
    'beetlesgallery.beetles_app.staging.StagingGateMiddleware',  # Staging only: sign in as the shared account
]

ROOT_URLCONF = 'beetlesgallery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Point to the internal templates folder inside beetlesgallery/
        'DIRS': [BASE_DIR / 'beetlesgallery' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Internal App Context Processor
                "beetlesgallery.beetles_app.context_processors.species_ref_status",
                "beetlesgallery.beetles_app.areas.areas_for_templates",
                "beetlesgallery.beetles_app.context_processors.game_player",
                "beetlesgallery.beetles_app.site_notice.context",
                "beetlesgallery.beetles_app.staging.context",
                "beetlesgallery.beetles_app.analytics.context",
            ],
        },
    },
]

WSGI_APPLICATION = 'beetlesgallery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Automatically configures database from environment variables (POSTGRES_USER, etc.)
DATABASES = {
    'default': dj_database_url.config(
        default=f"postgres://{os.environ.get('POSTGRES_USER', 'beetles_user')}:{os.environ.get('POSTGRES_PASSWORD', 'devpass')}@{os.environ.get('POSTGRES_HOST', 'db')}:{os.environ.get('POSTGRES_PORT', '5432')}/{os.environ.get('POSTGRES_DB', 'beetles_db')}",
        conn_max_age=600,
        conn_health_checks=True
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Cache lifetimes: hashed static files for a year, the rest for five minutes (beetlesgallery/cache_policy.py)
from beetlesgallery.cache_policy import whitenoise_add_headers
WHITENOISE_ADD_HEADERS_FUNCTION = whitenoise_add_headers
WHITENOISE_MAX_AGE = 5 * 60

# Point to the internal static folder inside beetlesgallery/
STATICFILES_DIRS = [
    BASE_DIR / "beetlesgallery" / "static",
]

# Media Files (User Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Beetles App Configuration ---

# Auth Redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "image_browser"
LOGOUT_REDIRECT_URL = "image_browser"
# The sign-in page says accounts were reset (they were, for the new access-request system) until this date.
# Empty turns the notice off.
ACCOUNT_RESET_NOTICE_UNTIL = os.environ.get("ACCOUNT_RESET_NOTICE_UNTIL", "2026-10-31")

# Access requests (beetles_app/access.py): who is emailed when someone asks for an account.
# They read and decide the requests on My Account -> Access Requests, so they need superuser accounts.
# Every active superuser who has an email address is also told, so keep the superuser list to people who should be.
ACCESS_REQUEST_RECIPIENTS = [
    address.strip()
    for address in os.environ.get("ACCESS_REQUEST_RECIPIENTS", "gmarais@ufl.edu").split(",")
    if address.strip()
]
# The address people use, for links in emails sent when nobody is making a request (the reminder command)
SITE_URL = os.environ.get("SITE_URL", "https://barkandambrosiagallery.org")
# Google Analytics (GA4) Measurement ID, e.g. G-XXXXXXXXXX. Only the live server sets it (in .env.prod). When it is
# empty (local, staging, tests) no analytics code and no cookie notice are rendered. See docs/analytics.md.
GA_MEASUREMENT_ID = os.environ.get("GA_MEASUREMENT_ID", "").strip()
PASSWORD_RESET_TIMEOUT = 7 * 24 * 60 * 60  # the "set your password" link in an approval email lasts a week

# Email. Set EMAIL_HOST (and the rest) in the server's .env to send real mail; without EMAIL_HOST,
# mail is written to the log instead of being sent.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
EMAIL_TIMEOUT = 10  # seconds; a mail server that does not answer must not hang a page
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend" if EMAIL_HOST else "django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "noreply@barkandambrosiagallery.org")

# The AI classifier service (used by the classifier page and "Generate AI recommendation" on the annotation page)
MODAL_API_URL = os.environ.get("MODAL_API_URL", "https://christophermarais--ibbi-api-fastapi-app.modal.run/analyze")

# Beetle ID game (beetles_app/game.py)
GAME_ROUND_SIZE = 10                  # items per round
GAME_FIRST_ITEMS = 2                  # a batch built while the player waits starts with these, the rest later (0: whole)
# Re-score other players on the Celery worker when someone finishes playing (on in production)
GAME_RECOMPUTE_IN_BACKGROUND = os.environ.get("GAME_RECOMPUTE_IN_BACKGROUND", "0" if DEBUG else "1") == "1"
# what the game is called on the site (one place to rename it)
GAME_DISPLAY_NAME = "Ambrosia Archive"
# where players report bugs and suggest ideas for the game
GAME_DISCUSSIONS_URL = "https://github.com/ChristopherMarais/barkandambrosiagallery/discussions/categories/beetle-id-game"
GAME_CALIBRATION_CHECKS = 20          # scored answers before a player counts as calibrated
GAME_CHECK_RATIO_NEW = 0.6            # share of validated (scored) items while calibrating
GAME_CHECK_RATIO_KNOWN = 0.2          # ... and afterwards
GAME_MIN_JUDGED_FOR_ACCURACY = 10     # judged ranks needed before an accuracy is shown
GAME_REPORT_MIN_JUDGED = 5            # scored answers before a group shows on a player's report
GAME_RESUME_HOURS = 12                # an unfinished round is picked up again within this time

# Focus: an unvalidated beetle counts as in the focus taxon when the species classifier gives it at least this much
# confidence at the focus rank (#375). The player is never told why a beetle was chosen.
GAME_FOCUS_AI_MIN = {"subfamily": 0.6, "tribe": 0.6, "genus": 0.5}

# Item difficulty (0 easy .. 1 hard): the target starts low and rises with every round
GAME_DIFFICULTY_START = 0.15
GAME_DIFFICULTY_PER_ROUND = 0.005
GAME_DIFFICULTY_SKILL_WEIGHT = 0.7    # reliable players get harder items: the target follows their rating
GAME_DIFFICULTY_MAX = 0.9
GAME_CANDIDATE_OVERSAMPLE = 6         # candidates drawn per slot before matching difficulty

# Trusted labels (beetles_app/game_trust.py).
# Expertise in a taxon scales with its size: so many validated images (all of them for one with fewer) of at least
# GAME_TRUST_CHILDREN_SHARE of its children with validated images (a genus's species, a tribe's genera, ...; rounded
# up), at least GAME_TRUST_MIN_JUDGED in total, and at least GAME_TRUST_MIN_ACCURACY of the answers right. Taxa with
# fewer than GAME_TRUST_MIN_JUDGED validated images can't be proven directly.
GAME_TRUST_IMAGES_PER_SPECIES = 5     # per child covered (the name predates #381)
GAME_TRUST_CHILDREN_SHARE = 0.75
GAME_TRUST_MIN_JUDGED = 10
GAME_TRUST_MIN_ACCURACY = 0.9
GAME_TRUST_Z = 1.96                   # only for ranking players (Wilson lower bound), not for proof
GAME_TRUST_SIBLINGS = 2               # related branches needed where a branch can't be tested
GAME_TRUST_MIN_VOTES = 1              # trusted players needed to back a label

# Upload Constraints
MAX_UPLOAD_SIZE = 10 * 1024 * 1024
MAX_UPLOAD_SIZE_XLSX = 10 * 1024 * 1024
MAX_UPLOAD_SIZE_CSV = 10 * 1024 * 1024  # metadata and update CSVs; keep in step with data-max-bytes in data_management.html
MAX_UPLOAD_SIZE_TAXONOMY = 100 * 1024 * 1024  # taxonomy reference CSVs; same
MAX_UPLOAD_SIZE_PREDICTIONS = 50 * 1024 * 1024  # classifier prediction CSVs (one row per ROI, ~70k rows is about 10-20 MB)
MAX_UPLOAD_SIZE_ZIP = 2 * 1024 * 1024 * 1024
MAX_UPLOAD_TOTAL_BYTES = 2 * 1024 * 1024 * 1024  # CSV + ZIP together; keep in step with data-max-bytes in data_management.html
DATA_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
FILE_UPLOAD_TEMP_DIR = MEDIA_ROOT / "tmp_uploads"
# Big files are uploaded in pieces of this size (beetles_app/chunked_upload.py): Cloudflare refuses requests over 100 MB
UPLOAD_CHUNK_BYTES = int(os.environ.get("UPLOAD_CHUNK_BYTES", 50 * 1024 * 1024))
# How long files that are no longer needed stay on disk (beetles_app/storage_cleanup.py, run nightly)
DOWNLOAD_RETENTION_DAYS = 14   # a finished download can be fetched for this long, then it is rebuilt on request
UPLOAD_ZIP_KEEP_DAYS = 7       # an imported upload's ZIP, once every image in it is in the gallery
FAILED_UPLOAD_KEEP_DAYS = 30   # ZIPs of rejected, failed or unfinished uploads
TEMP_FILE_KEEP_HOURS = 24      # leftovers of interrupted uploads and download builds

# Create temp dir if it doesn't exist
os.makedirs(FILE_UPLOAD_TEMP_DIR, exist_ok=True)

# Taxonomy Reference
VALID_SPECIES_PATH = "reference/valid_species.csv"
VALID_SPECIES_VERSION_CACHE_KEY = "valid_species:version"
VALID_SPECIES_VERSION_LABEL_CACHE_KEY = "valid_species:label"
VALID_SPECIES_UPDATING_CACHE_KEY = "valid_species:updating"

# Django doesn't chmod uploaded files or the folders it creates: they get the container's default modes (umask).
FILE_UPLOAD_PERMISSIONS = None
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None

# --- Celery Configuration ---
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# Heavy jobs (CSV uploads and updates, model predictions, building downloads) go to their own queue, which production runs one at a
# time at low CPU priority (the worker-heavy service), so they never hold up the game's quick background work
# (issue #383). A worker started without -Q only takes the default queue: in development run it with -Q celery,heavy.
CELERY_TASK_DEFAULT_QUEUE = "celery"
HEAVY_QUEUE = "heavy"
CELERY_TASK_ROUTES = {
    "beetlesgallery.beetles_app.tasks.process_upload_task": {"queue": HEAVY_QUEUE},
    "beetlesgallery.beetles_app.tasks.process_update_task": {"queue": HEAVY_QUEUE},
    "beetlesgallery.beetles_app.tasks.build_downloads_task": {"queue": HEAVY_QUEUE},
    "beetlesgallery.beetles_app.tasks.recompute_all_scores_task": {"queue": HEAVY_QUEUE},
    "beetlesgallery.beetles_app.tasks.import_predictions_task": {"queue": HEAVY_QUEUE},
}

# --- Cache Configuration ---
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_CACHE_URL", "redis://redis:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        }
    }
}
DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True

# --- Security Settings for Cloudflare ---
# Read from env, or default to empty list
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
# Remove empty strings just in case
CSRF_TRUSTED_ORIGINS = [origin for origin in CSRF_TRUSTED_ORIGINS if origin]

# --- Cloudflare & Proxy Configuration ---
# Trust the headers set by Cloudflare so Django knows the request is HTTPS
# This is critical to prevent "CSRF Verification Failed" errors.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- Session & Cookie Sharing ---
# Allow cookies to work across subdomains (e.g., .barkandambrosiagallery.org)
# This allows a user logged into 'www' to stay logged in on 'direct'.
# We read this from the environment so it doesn't break local development.
SESSION_COOKIE_DOMAIN = os.environ.get('SESSION_COOKIE_DOMAIN', None)
CSRF_COOKIE_DOMAIN = os.environ.get('SESSION_COOKIE_DOMAIN', None)

# --- Staging site (docs/staging.md) ---
# A copy of the site running `main` on its own database. Only the shared account below can sign in, nothing is
# emailed, and its cookies are its own, so a production sign-in never mixes with a staging one.
STAGING = os.environ.get("STAGING", "0") == "1"
STAGING_ACCOUNT = os.environ.get("STAGING_ACCOUNT", "stagedtesting")
STAGING_PASSWORD = os.environ.get("STAGING_PASSWORD", "gallerystaging")
if STAGING:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    SESSION_COOKIE_NAME = "staging_sessionid"
    CSRF_COOKIE_NAME = "staging_csrftoken"
    SESSION_COOKIE_DOMAIN = None
    CSRF_COOKIE_DOMAIN = None

# The live and staging sites are only reached over HTTPS (Cloudflare), so their sign-in and CSRF cookies are never
# sent over plain HTTP (manage.py check --deploy). Local runs with DEBUG keep plain cookies; SECURE_COOKIES=0/1 overrides.
IS_PRODUCTION = os.environ.get('DJANGO_DEBUG', 'False') == 'False'   # the live and staging sites run without DEBUG
SECURE_COOKIES = os.environ.get("SECURE_COOKIES", "1" if IS_PRODUCTION else "0") == "1"
SESSION_COOKIE_SECURE = SECURE_COOKIES
CSRF_COOKIE_SECURE = SECURE_COOKIES

# --- Django REST Framework Configuration ---
REST_FRAMEWORK = {
    # No pagination for now
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # For web frontend
        'rest_framework.authentication.TokenAuthentication',     # For API clients
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Require authentication
    ],
}