# Generated by Django 5.2.6 on 2025-10-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beetles',
            name='image_file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='beetles',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='thumb_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='thumb_small',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='beetles',
            name='thumb_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='image_file',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='thumb_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='thumb_small',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='thumb_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
