# Generated by Django 5.2.6 on 2025-10-08 13:58

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0002_beetles_image_file_beetles_image_height_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='beetles',
            index=models.Index(django.db.models.functions.text.Upper('depicts_specimen'), name='beetles_u_specimen_idx'),
        ),
        migrations.AddIndex(
            model_name='beetles',
            index=models.Index(django.db.models.functions.text.Upper('collection_country'), name='beetles_u_country_idx'),
        ),
        migrations.AddIndex(
            model_name='beetles',
            index=models.Index(django.db.models.functions.text.Upper('specimen_sex'), name='beetles_u_sex_idx'),
        ),
        migrations.AddIndex(
            model_name='beetles',
            index=models.Index(django.db.models.functions.text.Upper('specimen_type_status'), name='beetles_u_type_status_idx'),
        ),
    ]
