# Generated by Django 5.2.6 on 2025-10-10 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0003_beetles_beetles_u_specimen_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selection_mode', models.CharField(choices=[('ids', 'IDs'), ('query', 'Query')], db_index=True, max_length=8)),
                ('query_string', models.TextField(blank=True)),
                ('selected_ids_json', models.TextField(blank=True)),
                ('total_requested', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('tsv_file', models.FileField(blank=True, upload_to='downloads/results/%Y/%m')),
                ('zip_file', models.FileField(blank=True, upload_to='downloads/results/%Y/%m')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'status'], name='beetles_app_request_f1041e_idx')],
            },
        ),
    ]
