# Generated by Django 5.2.6 on 2025-10-20 19:42

import beetles_app.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0004_downloadjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beetles',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beetles_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beetles',
            name='update_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='update_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UpdateBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=beetles_app.models.updates_staging_path_xlsx)),
                ('original_filename', models.CharField(max_length=300)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('staging', 'Staging'), ('validating', 'Validating'), ('validated', 'Validation passed'), ('rejected', 'Validation failed'), ('applied', 'Applied'), ('apply_failed', 'Apply failed')], db_index=True, default='staging', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('species_version_at_validation', models.CharField(blank=True, max_length=64)),
                ('species_label_at_validation', models.CharField(blank=True, max_length=200)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_matched', models.PositiveIntegerField(default=0)),
                ('rows_changed', models.PositiveIntegerField(default=0)),
                ('rows_unchanged', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, upload_to=beetles_app.models.updates_reports_path)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update Batch',
                'verbose_name_plural': 'Update Batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploaded_by', 'status'], name='beetles_app_uploade_0a212e_idx')],
            },
        ),
    ]
