# Generated by Django 5.2.6 on 2025-10-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0005_beetles_last_updated_at_beetles_last_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beetles',
            name='depicts_valid_name_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbeetles',
            name='depicts_valid_name_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
