# Generated by Django 5.2.6 on 2025-11-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0006_alter_beetles_depicts_valid_name_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beetles',
            name='image_size_bytes',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='image_size_bytes',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
