# Generated by Django 5.0.1 on 2025-12-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0007_beetles_image_size_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='error_report_file',
            field=models.FileField(blank=True, help_text='Full validation error log for this batch.', null=True, upload_to='upload_error_logs/'),
        ),
    ]
