# Generated by Django 5.0.8 on 2026-01-09 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('full_path_at_import', models.TextField(help_text='Original path/filename of the first import of this image.')),
                ('image_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer', models.CharField(blank=True, max_length=255, null=True)),
                ('image_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo_usage_statement', models.TextField(blank=True, null=True)),
                ('image_date_taken', models.DateField(blank=True, null=True)),
                ('image_notes', models.TextField(blank=True, null=True)),
                ('image_has_multiple_individuals', models.BooleanField(blank=True, null=True)),
                ('aspect', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_in_ppmm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('image_size_bytes', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('image_file', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('thumb_small', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('thumb_width', models.PositiveIntegerField(blank=True, null=True)),
                ('thumb_height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='beetles',
            name='image_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='beetles_app.imageasset'),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='image_asset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beetles_app.imageasset'),
        ),
    ]
