# Generated by Django 5.0.8 on 2026-01-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0003_remove_beetles_full_path_at_import_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="downloadjob",
            old_name="tsv_file",
            new_name="csv_file",
        ),
    ]
