# Generated by Django 5.0.8 on 2026-01-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0004_rename_tsv_file_downloadjob_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='include_images',
            field=models.BooleanField(default=True, help_text='If False, generate CSV only (no ZIP).'),
        ),
    ]
