# Generated by Django 5.0.8 on 2026-02-13 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0005_downloadjob_include_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField(help_text='Normalized left edge position (0 = left side, 1 = right side)')),
                ('y', models.FloatField(help_text='Normalized top edge position (0 = top, 1 = bottom)')),
                ('width', models.FloatField(help_text='Normalized width (as fraction of image width, 0-1)')),
                ('height', models.FloatField(help_text='Normalized height (as fraction of image height, 0-1)')),
                ('label', models.CharField(blank=True, help_text='Species name, classification label, or other identifier', max_length=200)),
                ('confidence', models.FloatField(blank=True, help_text='AI model confidence score (0-1) for AI-generated boxes', null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual Annotation'), ('ai', 'AI Generated'), ('imported', 'Imported from External Tool')], default='manual', help_text='How this bounding box was created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Whether this annotation has been verified by a staff member')),
                ('validated_at', models.DateTimeField(blank=True, help_text='When this annotation was validated', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about this annotation')),
                ('beetle', models.ForeignKey(blank=True, help_text='Optional link to a cataloged specimen record if this box represents a known specimen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounding_boxes', to='beetles_app.beetles')),
                ('created_by', models.ForeignKey(help_text='User who created this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_annotations', to=settings.AUTH_USER_MODEL)),
                ('image_asset', models.ForeignKey(help_text='The image this bounding box is drawn on', on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='beetles_app.imageasset')),
                ('validated_by', models.ForeignKey(blank=True, help_text='Staff member who validated this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bounding Box',
                'verbose_name_plural': 'Bounding Boxes',
                'db_table': 'bounding_boxes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['image_asset', 'source'], name='bounding_bo_image_a_bb51c5_idx'), models.Index(fields=['created_by'], name='bounding_bo_created_2632ee_idx'), models.Index(fields=['is_validated'], name='bounding_bo_is_vali_207e71_idx'), models.Index(fields=['beetle'], name='bounding_bo_beetle__2d1b8c_idx')],
            },
        ),
    ]
