# Generated by Django 5.0.8 on 2026-02-19 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0006_boundingbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beetles',
            name='bbox_created_at',
            field=models.DateTimeField(blank=True, help_text='When this annotation was created', null=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='bbox_created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_beetle_bboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beetles',
            name='bbox_height',
            field=models.FloatField(blank=True, help_text='Normalized height (as fraction of image height, 0-1)', null=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='bbox_is_validated',
            field=models.BooleanField(default=False, help_text='Whether this annotation has been verified by a staff member'),
        ),
        migrations.AddField(
            model_name='beetles',
            name='bbox_label',
            field=models.CharField(blank=True, help_text='Species name, classification label, or other identifier', max_length=200),
        ),
        migrations.AddField(
            model_name='beetles',
            name='bbox_validated_at',
            field=models.DateTimeField(blank=True, help_text='When this annotation was validated', null=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='bbox_validated_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who validated this annotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_beetle_bboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beetles',
            name='bbox_width',
            field=models.FloatField(blank=True, help_text='Normalized width (as fraction of image width, 0-1)', null=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='bbox_x',
            field=models.FloatField(blank=True, help_text='Normalized left edge position (0 = left side, 1 = right side)', null=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='bbox_y',
            field=models.FloatField(blank=True, help_text='Normalized top edge position (0 = top, 1 = bottom)', null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_created_at',
            field=models.DateTimeField(blank=True, help_text='When this annotation was created', null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this annotation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_height',
            field=models.FloatField(blank=True, help_text='Normalized height (as fraction of image height, 0-1)', null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_is_validated',
            field=models.BooleanField(default=False, help_text='Whether this annotation has been verified by a staff member'),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_label',
            field=models.CharField(blank=True, help_text='Species name, classification label, or other identifier', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_validated_at',
            field=models.DateTimeField(blank=True, help_text='When this annotation was validated', null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_validated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Staff member who validated this annotation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_width',
            field=models.FloatField(blank=True, help_text='Normalized width (as fraction of image width, 0-1)', null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_x',
            field=models.FloatField(blank=True, help_text='Normalized left edge position (0 = left side, 1 = right side)', null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='bbox_y',
            field=models.FloatField(blank=True, help_text='Normalized top edge position (0 = top, 1 = bottom)', null=True),
        ),
    ]
