# Generated by Django 5.0.8 on 2026-02-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0007_add_bbox_fields_to_beetles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoundingBox',
        ),
    ]
