# Generated by Django 5.0.8 on 2026-02-26 23:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0008_drop_boundingbox_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locked_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the lock was acquired')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last activity timestamp (for auto-expiry)')),
                ('image_asset', models.OneToOneField(help_text='The image that is currently locked', on_delete=django.db.models.deletion.CASCADE, related_name='active_lock', to='beetles_app.imageasset')),
                ('locked_by', models.ForeignKey(help_text='User who has this image open', on_delete=django.db.models.deletion.CASCADE, related_name='image_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image Lock',
                'verbose_name_plural': 'Image Locks',
                'db_table': 'image_locks',
                'indexes': [models.Index(fields=['locked_by', 'updated_at'], name='image_locks_locked__594053_idx')],
            },
        ),
    ]
