# Generated by Django 5.0.8 on 2026-03-10 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0009_imagelock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('category_id', models.IntegerField(help_text='Numeric ID used in YOLO/COCO.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supercategory', models.CharField(db_index=True, default='beetle', max_length=100)),
            ],
            options={
                'verbose_name': 'Category Mapping',
                'verbose_name_plural': 'Category Mappings',
                'db_table': 'category_mapping',
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('valid_species_id', models.CharField(db_index=True, help_text='Original identifier mapping to valid_species.csv', max_length=255, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('subfamily', models.CharField(blank=True, max_length=100, null=True)),
                ('tribe', models.CharField(blank=True, max_length=100, null=True)),
                ('subtribe', models.CharField(blank=True, max_length=100, null=True)),
                ('genus', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('subspecies', models.CharField(blank=True, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('authority_year', models.CharField(blank=True, max_length=50, null=True)),
                ('original_genus', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taxon',
                'verbose_name_plural': 'Taxa',
                'db_table': 'taxon',
                'indexes': [models.Index(fields=['scientific_name'], name='taxon_scienti_950316_idx'), models.Index(fields=['genus', 'species'], name='taxon_genus_1bdba4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(db_index=True, help_text='Original identifier mapping to described_names.csv', max_length=255, unique=True)),
                ('described_scientific_name', models.CharField(db_index=True, max_length=255)),
                ('described_scientific_name_authority', models.CharField(blank=True, max_length=255, null=True)),
                ('genus', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('subspecies', models.CharField(blank=True, max_length=100, null=True)),
                ('authority', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxon', models.ForeignKey(help_text='The valid taxon this synonym maps to.', on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='beetles_app.taxon')),
            ],
            options={
                'verbose_name': 'Synonym',
                'verbose_name_plural': 'Synonyms',
                'db_table': 'synonym',
            },
        ),
        migrations.AddField(
            model_name='beetles',
            name='taxon',
            field=models.ForeignKey(blank=True, help_text='Relational link to the materialized taxonomy tree.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimens', to='beetles_app.taxon'),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='taxon',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Relational link to the materialized taxonomy tree.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beetles_app.taxon'),
        ),
        migrations.AddIndex(
            model_name='beetles',
            index=models.Index(fields=['image_asset', 'id'], name='beetles_asset_id_idx'),
        ),
    ]
