# Generated by Django 5.0.8 on 2026-03-11 04:01

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0010_categorymapping_taxon_synonym_beetles_taxon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beetles',
            name='depicts_described_name_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beetles',
            name='depicts_valid_name_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbeetles',
            name='depicts_described_name_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbeetles',
            name='depicts_valid_name_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='genus',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='original_genus',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='scientific_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='species',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='subfamily',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='subtribe',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='tribe',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='synonym',
            index=django.contrib.postgres.indexes.GinIndex(fields=['described_scientific_name'], name='syn_desc_name_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=django.contrib.postgres.indexes.GinIndex(fields=['original_genus'], name='taxon_orig_genus_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
