# Generated by Django 5.0.8 on 2026-03-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0011_alter_beetles_depicts_described_name_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beetles',
            options={'verbose_name': 'Region of Interest (ROI)', 'verbose_name_plural': 'Regions of Interest (ROIs)'},
        ),
        migrations.AlterModelOptions(
            name='historicalbeetles',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Region of Interest (ROI)', 'verbose_name_plural': 'historical Regions of Interest (ROIs)'},
        ),
    ]
