# Generated by Django 5.0.8 on 2026-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0012_alter_beetles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beetles',
            name='bbox_label',
            field=models.CharField(blank=True, help_text='Species name, classification label, or other identifier', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbeetles',
            name='bbox_label',
            field=models.CharField(blank=True, help_text='Species name, classification label, or other identifier', max_length=200, null=True),
        ),
    ]
