# Generated by Django 5.0.8 on 2026-03-13 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0013_alter_beetles_bbox_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryMapping',
        ),
        migrations.RemoveField(
            model_name='beetles',
            name='bbox_label',
        ),
        migrations.RemoveField(
            model_name='historicalbeetles',
            name='bbox_label',
        ),
        migrations.AddField(
            model_name='imageasset',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Has this image been fully reviewed/validated?'),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this image or its metadata', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_image_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
