# Generated by Django 5.0.8 on 2026-03-14 23:21

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0014_delete_categorymapping_remove_beetles_bbox_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beetles',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beetles',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft deletion flag.'),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbeetles',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft deletion flag.'),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft deletion flag. If true, hidden from UI.'),
        ),
        migrations.CreateModel(
            name='HistoricalImageAsset',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('image_sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('full_path_at_import', models.TextField(help_text='Original path/filename of the first import of this image.')),
                ('image_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('photographer', models.CharField(blank=True, max_length=255, null=True)),
                ('image_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo_usage_statement', models.TextField(blank=True, null=True)),
                ('image_date_taken', models.DateField(blank=True, null=True)),
                ('image_notes', models.TextField(blank=True, null=True)),
                ('image_has_multiple_individuals', models.BooleanField(blank=True, null=True)),
                ('resolution_in_ppmm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('image_size_bytes', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('image_file', models.TextField(blank=True, max_length=500, null=True)),
                ('thumb_small', models.TextField(blank=True, max_length=500, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('thumb_width', models.PositiveIntegerField(blank=True, null=True)),
                ('thumb_height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Has this image been fully reviewed/validated?')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft deletion flag. If true, hidden from UI.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last updated this image or its metadata', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical image asset',
                'verbose_name_plural': 'historical image assets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
