# Generated by Django 5.0.8 on 2026-03-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0015_beetles_deleted_at_beetles_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('category_id', models.IntegerField(help_text='Numeric ID used in YOLO/COCO.', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supercategory', models.CharField(db_index=True, default='beetle', max_length=100)),
            ],
            options={
                'verbose_name': 'Category Mapping',
                'verbose_name_plural': 'Category Mappings',
                'db_table': 'category_mapping',
            },
        ),
    ]
