# Generated by Django 5.0.8 on 2026-09-16 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beetles_app", "0016_categorymapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="PathogenInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_block_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "record_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "beetle_host",
                    models.CharField(
                        db_index=True,
                        help_text="Scientific name of beetle host",
                        max_length=255,
                    ),
                ),
                (
                    "beetle_host_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "pathogen",
                    models.CharField(
                        db_index=True,
                        help_text="Pathogen or parasite taxon",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Fungi, Nematode, Microsporidia, etc.",
                        max_length=64,
                    ),
                ),
                (
                    "organism_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "infection_site",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ecological_relationship",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                (
                    "identification_method",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "validation_type",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "experimental_conditions",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "country_or_region",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=16, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("doi_or_full_text", models.TextField(blank=True, null=True)),
                (
                    "full_text_status",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pathogen Interaction",
                "verbose_name_plural": "Pathogen Interactions",
                "db_table": "pathogen_interactions",
                "ordering": ["beetle_host", "pathogen"],
            },
        ),
    ]
