# Generated by Django 5.0.14 on 2026-09-30 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0020_game_feedback_reports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valid_species_id", models.CharField(db_index=True, max_length=255)),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Model confidence in this species, 0 to 1."
                    ),
                ),
                (
                    "top_k",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Further candidates, best first: [{"valid_species_id": "1733", "confidence": 0.08}, ...]',
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="beetles_app.beetles",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        help_text="The taxon for valid_species_id when it was uploaded.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predictions",
                        to="beetles_app.taxon",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "model_prediction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="modelprediction",
            constraint=models.UniqueConstraint(
                fields=("roi", "model_name", "model_version"),
                name="model_prediction_roi_model_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelprediction",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="model_prediction_confidence_0_1",
            ),
        ),
    ]
