# Generated by Django 5.0.14 on 2026-09-30 15:48

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0022_accessrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pathogeninteraction",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who accepted or uploaded it (empty for the published dataset).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pathogeninteraction",
            name="origin",
            field=models.CharField(
                choices=[
                    ("dataset", "Published dataset (v1.0)"),
                    ("proposal", "Accepted proposal"),
                    ("upload", "Uploaded by a curator"),
                ],
                db_index=True,
                default="dataset",
                help_text="Where the row came from. Reloading the dataset only ever touches 'dataset' rows.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="InteractionProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "beetle_name",
                    models.CharField(
                        help_text="The beetle's valid name in the species list (a source that uses a synonym is matched to it).", max_length=255
                    ),
                ),
                (
                    "beetle_valid_species_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="valid_species_id when the beetle is in the species list.",
                        max_length=64,
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(
                        help_text="The other organism: a fungus, host tree, nematode...",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Fungi, Nematode, Host plant, Mite...",
                        max_length=64,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="pathogen, parasite, symbiont, host plant...",
                        max_length=128,
                    ),
                ),
                (
                    "source_key",
                    models.CharField(
                        help_text="What makes a source unique: its lower-case DOI, else 'pmid:...' or its URL.",
                        max_length=300,
                    ),
                ),
                ("source_doi", models.CharField(blank=True, max_length=255)),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Where a reviewer reads it.",
                        max_length=500,
                    ),
                ),
                ("source_title", models.TextField(blank=True)),
                (
                    "source_authors",
                    models.CharField(
                        blank=True,
                        help_text="As the source lists them, e.g. 'Smith J, Jones K'.",
                        max_length=500,
                    ),
                ),
                ("source_journal", models.CharField(blank=True, max_length=255)),
                (
                    "source_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "source_db",
                    models.CharField(
                        blank=True,
                        help_text="europepmc, globi, upload...",
                        max_length=30,
                    ),
                ),
                ("open_access", models.BooleanField(blank=True, null=True)),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="The sentence(s) in the source that state it.",
                    ),
                ),
                (
                    "evidence_location",
                    models.CharField(
                        blank=True,
                        help_text="title, abstract, full text",
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="The collector's confidence, 0 to 1.",
                        null=True,
                    ),
                ),
                (
                    "collector",
                    models.CharField(
                        blank=True,
                        help_text="What proposed it, and its version.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Waiting for review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="proposed",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_as",
                    models.ForeignKey(
                        blank=True,
                        help_text="The dataset row created when this was accepted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposals",
                        to="beetles_app.pathogeninteraction",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_proposals",
                        to="beetles_app.taxon",
                    ),
                ),
            ],
            options={
                "db_table": "interaction_proposal",
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-score"], name="interaction_proposal_queue"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="interactionproposal",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("beetle_name"),
                django.db.models.functions.text.Lower("partner_name"),
                models.F("source_key"),
                name="interaction_proposal_one_per_claim_and_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="interactionproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score__isnull", True),
                    models.Q(("score__gte", 0), ("score__lte", 1)),
                    _connector="OR",
                ),
                name="interaction_proposal_score_0_1",
            ),
        ),
    ]
