# Generated by Django 5.0.14 on 2026-10-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0033_rename_alternative_id_alias_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="beetles",
            name="label_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vial_label", "Vial / specimen label"),
                    ("taxonomist", "Taxonomist examined it"),
                    ("external", "External database or website"),
                    ("game_consensus", "Game consensus accepted by a curator"),
                ],
                default="",
                help_text="Where the name came from. Blank: not recorded (names given before this was kept).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="beetles",
            name="label_source_detail",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who examined it, or which database or website (name or URL).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicalbeetles",
            name="label_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vial_label", "Vial / specimen label"),
                    ("taxonomist", "Taxonomist examined it"),
                    ("external", "External database or website"),
                    ("game_consensus", "Game consensus accepted by a curator"),
                ],
                default="",
                help_text="Where the name came from. Blank: not recorded (names given before this was kept).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalbeetles",
            name="label_source_detail",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Who examined it, or which database or website (name or URL).",
                max_length=255,
            ),
        ),
    ]
