# Generated by Django 5.0.14 on 2026-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beetles_app", "0035_site_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepreference",
            name="proposals_notice_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the player saw 'Your labels now go to the curators' (shown once).",
                null=True,
            ),
        ),
    ]
