# Generated by Django 5.0.14 on 2026-10-05 04:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

# Old label sources -> identification tiers. A vial label counts as a taxonomist's ID; game consensus a curator
# accepted counts as an expert's.
OLD_TO_TIER = {"vial_label": "taxonomist", "game_consensus": "expert"}
VIAL_NOTE = "Vial / specimen label"


def to_tiers(apps, schema_editor):
    Beetles = apps.get_model("beetles_app", "Beetles")
    RoiName = apps.get_model("beetles_app", "RoiName")
    Taxon = apps.get_model("beetles_app", "Taxon")
    vial = Beetles.objects.filter(label_source="vial_label")
    vial.filter(label_source_detail="").update(label_source_detail=VIAL_NOTE)
    for old, tier in OLD_TO_TIER.items():
        Beetles.objects.filter(label_source=old).update(label_source=tier)
    # Validated names are an expert's at least: only Taxonomist and Expert IDs are validated
    Beetles.objects.filter(bbox_is_validated=True, depicts_valid_name_id__isnull=False).exclude(
        label_source__in=["taxonomist", "expert"]).update(label_source="expert")
    # Every ROI's current name becomes its first recorded name
    taxa = dict(Taxon.objects.values_list("valid_species_id", "id"))
    rows = []
    named = Beetles.objects.filter(depicts_valid_name_id__isnull=False).exclude(depicts_valid_name_id="").values_list(
        "id", "depicts_valid_name_id", "label_source", "label_source_detail", "last_updated_by_id", "last_updated_at")
    for roi_id, name, tier, detail, user_id, when in named.iterator(chunk_size=5000):
        kwargs = dict(roi_id=roi_id, valid_species_id=name, taxon_id=taxa.get(name), tier=tier or "",
                      detail=(detail or "")[:255], added_by_id=user_id)
        if when:
            kwargs["created_at"] = when
        rows.append(RoiName(**kwargs))
        if len(rows) >= 5000:
            RoiName.objects.bulk_create(rows)
            rows = []
    RoiName.objects.bulk_create(rows)


def back(apps, schema_editor):
    Beetles = apps.get_model("beetles_app", "Beetles")
    Beetles.objects.filter(label_source="community").update(label_source="")


class Migration(migrations.Migration):
    DATA_MIGRATION_REVIEWED = (
        "Rewrites Beetles.label_source to the new tiers (vial_label -> taxonomist, game_consensus -> expert, and "
        "validated named ROIs without a taxonomist/expert tier -> expert) and adds one RoiName row per named ROI "
        "(its current name). Nothing is deleted; a vial label keeps 'Vial / specimen label' as its detail."
    )

    dependencies = [
        ("beetles_app", "0037_area_grants_for_existing_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="beetles",
            name="label_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("taxonomist", "Taxonomist ID"),
                    ("expert", "Expert ID"),
                    ("community", "Community ID"),
                    ("external", "External ID"),
                ],
                default="",
                help_text="How reliable the name is (identification tier). Blank: No ID (not recorded).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbeetles",
            name="label_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("taxonomist", "Taxonomist ID"),
                    ("expert", "Expert ID"),
                    ("community", "Community ID"),
                    ("external", "External ID"),
                ],
                default="",
                help_text="How reliable the name is (identification tier). Blank: No ID (not recorded).",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RoiName",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("valid_species_id", models.CharField(max_length=255)),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("taxonomist", "Taxonomist ID"),
                            ("expert", "Expert ID"),
                            ("community", "Community ID"),
                            ("external", "External ID"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "detail",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who, or which database / website.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="beetles_app.beetles",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="beetles_app.taxon",
                    ),
                ),
            ],
            options={
                "db_table": "roi_name",
                "ordering": ["roi", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["roi", "-created_at"], name="roi_name_roi_recent"
                    )
                ],
            },
        ),
        migrations.RunPython(to_tiers, back),
    ]
