# Generated by Django 5.0.8

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0038_identification_tiers'),
        ('beetles_app', '0039_prediction_upload'),
    ]

    operations = [
    ]
