# Generated by Django 5.0.8 on 2026-10-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0045_gamepreference_board_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanswer',
            name='mode',
            field=models.CharField(choices=[('classify', 'Classify'), ('pair', 'Compare pairs'), ('odd', 'Imposter Picker'), ('select', 'Find Them All'), ('mixed', 'All modes')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gamepreference',
            name='play_mode',
            field=models.CharField(choices=[('both', 'All modes'), ('classify', 'Identification'), ('pair', 'Similarity'), ('odd', 'Imposter Picker'), ('select', 'Find Them All')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='mode',
            field=models.CharField(choices=[('classify', 'Classify'), ('pair', 'Compare pairs'), ('odd', 'Imposter Picker'), ('select', 'Find Them All'), ('mixed', 'All modes')], db_index=True, max_length=10),
        ),
    ]
