# Generated by Django 5.0.8 on 2026-10-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0050_game_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameanswer',
            name='seen_before',
            field=models.BooleanField(default=False, help_text="The player had been shown this beetle's names before (the review after an answer names every beetle, #541), so it came back after a wait. Earns full points, but is left out of accuracy and expertise, which count only beetles named unseen."),
        ),
    ]
