# Generated by Django 5.0.8 on 2026-10-06 05:41
# The games' names again (#538): Odd One Out (back from Imposter Picker) and Naming (was Identification). Labels only.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beetles_app', '0052_gameanswer_seen_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameanswer',
            name='mode',
            field=models.CharField(choices=[('classify', 'Classify'), ('pair', 'Compare pairs'), ('odd', 'Odd One Out'), ('select', 'Find Them All'), ('mixed', 'All modes')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gamepreference',
            name='play_mode',
            field=models.CharField(choices=[('both', 'All modes'), ('classify', 'Naming'), ('pair', 'Similarity'), ('odd', 'Odd One Out'), ('select', 'Find Them All')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='mode',
            field=models.CharField(choices=[('classify', 'Classify'), ('pair', 'Compare pairs'), ('odd', 'Odd One Out'), ('select', 'Find Them All'), ('mixed', 'All modes')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='gridstep',
            name='game',
            field=models.CharField(choices=[('odd', 'Odd One Out'), ('select', 'Find Them All')], max_length=10),
        ),
    ]
