# Generated by Django 5.0.1 on 2025-09-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('pmid', models.CharField(blank=True, max_length=250, null=True)),
                ('pmcid', models.CharField(blank=True, max_length=250, null=True)),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('author_full_name', models.TextField(blank=True, null=True)),
                ('author_affiliation_details', models.TextField(blank=True, null=True)),
                ('journal_title', models.TextField(blank=True, null=True)),
                ('journal_issn', models.CharField(blank=True, max_length=250, null=True)),
                ('journal_issue', models.CharField(blank=True, max_length=250, null=True)),
                ('journal_volume', models.CharField(blank=True, max_length=250, null=True)),
                ('journal_year_of_publication', models.CharField(blank=True, max_length=250, null=True)),
                ('abstract_text', models.TextField(blank=True, null=True)),
                ('publication_status', models.CharField(blank=True, max_length=250, null=True)),
                ('language', models.CharField(blank=True, max_length=250, null=True)),
                ('pub_model', models.CharField(blank=True, max_length=250, null=True)),
                ('pub_type_list', models.TextField(blank=True, null=True)),
                ('grants_list', models.TextField(blank=True, null=True)),
                ('full_text_url_list', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'space_literature',
            },
        ),
    ]
